version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    container_name: ticketsmail-app
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - ticketsmail-network

networks:
  ticketsmail-network:
    driver: bridge